## test.yml

name: Main workflow
on: [push, pull_request]
permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 24.3
          - 24.4
          - 24.5
          - 25.1
          - 25.3
          - 26.1
          - 26.2
          - 26.3
          - 27.1
          - 27.2
          - 28.1
          - 28.2
          - snapshot
        include:
          - emacs_version: 'snapshot'
            allow_failure: true
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Install Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - name: Run tests
      if: matrix.allow_failure != true
      run: 'make && make test'

    - name: Run tests (allow failure)
      if: matrix.allow_failure == true
      run: 'make && make test || true'
