# Dockerfile References: https://docs.docker.com/engine/reference/builder/
#
# Build the container by running:
#
#    $ docker build [-t name:here] .
#


#
# Select the specified base image.
#
FROM debian:buster

#
# Set the working-directory inside the container.
#
WORKDIR /srv
