#!/bin/sh
#
# Some of the files/modes which are in this repository are hosted on github,
# this simple script updates them from their source-location if so.
#
# Of course it is possible that the modes will be moved, or will be removed
# if that is the case and these calls fail then we'll be able to retrieve the
# old versions via git.
#
# If this host has `go` installed upon it we'll also install/update the
# appropriate tools.
#
# Steve
# --

wget -O "lang/lua-mode.el"  https://raw.githubusercontent.com/immerrr/lua-mode/master/lua-mode.el

wget -O "lang/markdown-mode.el" https://raw.githubusercontent.com/jrblevin/markdown-mode/master/markdown-mode.el

wget -O "lang/monkey.el" https://raw.githubusercontent.com/skx/monkey/master/emacs/monkey.el

wget -O "lang/puppet-mode.el" https://raw.githubusercontent.com/voxpupuli/puppet-mode/master/puppet-mode.el

wget -O "lang/web-mode.el" https://github.com/fxbois/web-mode/raw/master/web-mode.el

wget -O "lang/cfengine.el" https://raw.githubusercontent.com/cfengine/core/master/contrib/cfengine.el



if [ -x /opt/go/bin/go ]; then

    # used for formatting code
    go get -u golang.org/x/tools/cmd/goimports
    go install golang.org/x/tools/cmd/goimports

    # Used for jumping to definitions.
    go get -u github.com/rogpeppe/godef
    go install github.com/rogpeppe/godef

else

    echo "Go is not installed upon this host"

fi
